<?php
/*------------------------------------------------------------------------
 # SNS RevolutionSlider - Version 1.0
 * Copyright (C) 2013 The SNS Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: SNS Theme
 * Websites: http://www.snstheme.com
-------------------------------------------------------------------------*/
$config = $this->getConfigObject();
$uq = rand().time();
?>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-page-carousel')->toHtml(); ?>
	