<div class="modal fade" id="loginPopUpModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="loginModalLabel"><?php echo $this->__('Login Form'); ?></h4>
			</div>
			<div class="modal-body">
				<div class="content">
					<div class="row">
						<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
						<?php echo $this->getChildHtml('customer.form.login.extra')?>
						<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="plogin-form">
							<?php echo $this->getBlockHtml('formkey'); ?>
							<div class="col-xs-12 col-md-12">
								<div class="bs-callout bs-callout-info ">
									<h2 class="td-section"><?php echo $this->__('Login') ?></h2>
									<p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
									<label for="email" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
									<div class="form-group">
										<input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="pemail" class="form-control required-entry validate-email" placeholder="<?php echo $this->__('Email') ?>" title="<?php echo $this->__('Email Address') ?>">
									</div>
									<label for="pass" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
									<div class="form-group">
										<input type="password" name="login[password]" class="form-control required-entry validate-password" id="ppass" placeholder="<?php echo $this->__('Password') ?>" title="<?php echo $this->__('Password') ?>">
									</div>
									<?php echo $this->getChildHtml('form.additional.info'); ?>
									<?php echo $this->getChildHtml('persistent.remember.me'); ?>
									<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
									<button type="submit" class="btn btn-td-info btn-md floatright" data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><?php echo $this->__('Login') ?></button>
									<a data-toggle="modal" data-target="#registerPopUpModal"><button type="button" class="btn btn-td-grey btn-md floatright btn-margin-rt" data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Sign up') ?>" id="psignup"><?php echo $this->__('Sign up') ?></button></a>
									<div class="clearfix"></div>
								</div>
							</div>
							
							<?php if (Mage::helper('checkout')->isContextCheckout()): ?>
								<input name="context" type="hidden" value="checkout" />
							<?php endif; ?>
						</form>
					</div>
					<script type="text/javascript">
					//<![CDATA[
						var dataForm = new VarienForm('plogin-form', true);
					//]]>
					</script>
				</div>
			</div>
			<div class="modal-footer">
				<div class="float-left" id="login-closing-notification"></div>
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

<!--- register form --->
<div class="modal fade" id="registerPopUpModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="registerModalLabel"><?php echo $this->__('Register Form'); ?></h4>
			</div>
			<div class="modal-body">
				<div class="content">
					<div class="row">
						<?php echo $this->getChildHtml('form_fields_before') ?>
						<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
						<form action="" method="post" id="pform-validate">
							<div class="col-xs-12 col-md-12">
								<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
								<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
								<div class="bs-callout bs-callout-info ">
									<h2 class="td-section"><?php echo $this->__('Sign up') ?></h2>

									<?php // echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

									<label class="required" for="firstname"><?php echo $this->__('First Name ') ?><em>*</em></label>
									<div class="form-group">
										<input type="text" title="<?php echo $this->__('First Name ') ?>" placeholder="<?php echo $this->__('First Name') ?>" class="form-control required-entry" id="firstname" value="" name="firstname">
									</div>
									
									<label class="required" for="email_address"><?php echo $this->__('Last Name ') ?><em>*</em></label>
									<div class="form-group">
										<input type="text" title="<?php echo $this->__('Last Name ') ?>" placeholder="<?php echo $this->__('Last Name') ?>" class="form-control required-entry" id="lastname" value="" name="lastname">
									</div>
									
									
									<label class="required" for="email_address"><?php echo $this->__('Email Address ') ?><em>*</em></label>
									<div class="form-group">
										<input type="text" title="<?php echo $this->__('Email Address ') ?>" placeholder="<?php echo $this->__('Email') ?>" class="form-control required-entry validate-email" id="premail" value="<?php // echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" name="email">
									</div>
									
									<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
									<?php if ($_dob->isEnabled()): ?>
										<?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
									<?php endif ?>
									<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
									<?php if ($_taxvat->isEnabled()): ?>
										<?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
									<?php endif ?>
									<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
									<?php if ($_gender->isEnabled()): ?>
										<?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?>
									<?php endif ?>
									
									 <?php if($this->getShowAddressFields()): ?>
										<div class="fieldset">
											<input type="hidden" name="create_address" value="1" />
											<h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
											<ul class="form-list">
												<li class="fields">
													<div class="field">
														<label for="company"><?php echo $this->__('Company') ?></label>
														<div class="input-box">
															<input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
														</div>
													</div>
													<div class="field">
														<label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
														<div class="input-box">
															<input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
														</div>
													</div>
												</li>
											<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
												<li class="wide">
													<label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
													<div class="input-box">
														<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
													</div>
												</li>
											<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
											<?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
												<li class="wide">
													<div class="input-box">
														<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
													</div>
												</li>
											<?php endfor; ?>
												<li class="fields">
													<div class="field">
														<label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
														<div class="input-box">
															<input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
														</div>
													</div>
													<div class="field">
														<label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
														<div class="input-box">
															<select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
																<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
															</select>
															<script type="text/javascript">
															//<![CDATA[
																$('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
															//]]>
															</script>
															<input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
														</div>
													</div>
												</li>
												<li class="fields">
													<div class="field">
														<label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
														<div class="input-box">
															<input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
														</div>
													</div>
													<div class="field">
														<label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
														<div class="input-box">
															<?php echo $this->getCountryHtmlSelect() ?>
														</div>
													</div>
												</li>
											</ul>
											<input type="hidden" name="default_billing" value="1" />
											<input type="hidden" name="default_shipping" value="1" />
										</div>
									<?php endif; ?>
									
									<label class="required" for="password"><?php echo $this->__('Password') ?><em>*</em></label>
									<div class="form-group">
										<input type="password" title="<?php echo $this->__('Password') ?>" placeholder="Password" id="prpassword" class="form-control required-entry validate-password" name="password">
									</div>
									<label class="required" for="confirmation"><?php echo $this->__('Confirm Password') ?><em>*</em></label>
									<div class="form-group">
										<input type="password" title="<?php echo $this->__('Confirm Password') ?>" placeholder="Password" id="confirmation" class="form-control required-entry validate-cpassword" name="confirmation">
									</div>
									<?php // if ($this->isNewsletterEnabled()): ?>
									<div class="checkbox">
										<label>
											<input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"class="checkbox" /><?php echo $this->__(' Newsletter Sign up') ?> 
										</label>
									</div>
									<?php // endif; ?>
									<?php echo $this->getChildHtml('form.additional.info'); ?>
									<?php echo $this->getChildHtml('persistent.remember.me'); ?>
									<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

									<button title="<?php echo $this->__('Submit') ?>" data-placement="top" data-toggle="tooltip" class="btn btn-td-info btn-md floatright" type="submit" data-original-title="Sign up"><?php echo $this->__('Sign up') ?></button>
									<div class="clearfix"></div>
									
									<?php if (Mage::helper('checkout')->isContextCheckout()): ?>
										<input name="context" type="hidden" value="checkout" />
									<?php endif; ?>
								</div>
							</div>
						</form>
						<script type="text/javascript">
						//<![CDATA[
							var dataForm = new VarienForm('pform-validate', true);
							<?php if($this->getShowAddressFields()): ?>
							new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
							<?php endif; ?>
						//]]>
						</script>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<div class="float-left" id="register-closing-notification"></div>
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
<!--- end registe form --->
					
<script type="text/javascript">
jQuery(document).ready(function(){
	
	jQuery('#pemail').val('');
	jQuery('#ppass').val('');
	jQuery('#prpassword').val('');
	jQuery('#premail').val('');
	/* Login ajax */
		jQuery('#psignup').on('click',function(){
			jQuery( "#loginPopUpModal" ).removeClass('in');
			jQuery( "#loginPopUpModal" ).attr( "aria-hidden",true);	
			jQuery('#loginPopUpModal').hide();
			jQuery( '.modal-backdrop').remove();
		});
        jQuery('#plogin-form').submit(function(event){
            event.preventDefault();
            if(!jQuery('#plogin-form div input').hasClass('validation-failed')){
                var data = jQuery('#plogin-form').serialize();
				jQuery('#sns_ajaxfilter .bg').height('100%');
				jQuery('#sns_ajaxfilter').fadeIn(300);
				jQuery.ajax({
                      url: "<?php echo $this->getUrl('ajaxlogin/account/pLogin') ?>",
                      type : 'post',
                      data: data,
                      success: function(data){
                          
                    	  //alert(JSON.stringify(data));
                    	  //alert(data);
                    	  var parsedJson = jQuery.parseJSON(data);                      
                          //alert(parsedJson.message);
                          if(parsedJson.message){
							  jQuery("#loginModalLabel").text(parsedJson.message);
                        	 // new Messi(parsedJson.message);
                          }
                          if(parsedJson.success){
							jQuery("#loginModalLabel").text('Login successfully');
							jQuery("#login-closing-notification").html('<div class="vspace8 clearfix"></div><p>This window will automatically close in few seconds</p>');
							// jQuery( "#loginPopUpModal" ).removeClass('in');
							// jQuery( ".modal-backdrop" ).removeClass('in');
							// jQuery( "#loginPopUpModal" ).attr( "aria-hidden",true);	
							// jQuery('#loginPopUpModal').hide();
							// jQuery( '.modal-backdrop').remove();
							// $currentUrl = jQuery(location).attr('href');
							location.reload();
                        	// new Messi('Login successfully');
							 
                        	 //alert(parsedJson.success);
                        	 // window.location = parsedJson.url;
							 
                         }
						 jQuery('#sns_ajaxfilter .bg').height('100%');
						 jQuery('#sns_ajaxfilter').fadeOut(600);
                          
                            //jQuery('#newsletter').val('');
                      }
                });
            }
        });

		/* Create account ajax */
        jQuery('#pform-validate').submit(function(event){
            event.preventDefault();
            if(!jQuery('#pform-validate div input').hasClass('validation-failed')){
                var data = jQuery('#pform-validate').serialize();
                jQuery('#sns_ajaxfilter .bg').height('100%');
				jQuery('#sns_ajaxfilter').fadeIn(300);
                jQuery.ajax({
                      url: "<?php echo $this->getUrl('ajaxlogin/account/pCreate') ?>",
                      type : 'post',
                      data: data,
                      success: function(data){
                    	  //alert(JSON.stringify(data));
                    	  var parsedJson = jQuery.parseJSON(data);                      
                          //alert(parsedJson.message);
                          if(parsedJson.message){
							  jQuery("#registerModalLabel").text(parsedJson.message);
                        	 // new Messi(parsedJson.message);
                          }
                          if(parsedJson.success){
							// jQuery( "#registerPopUpModal" ).removeClass('in');
							// jQuery( "#registerPopUpModal" ).attr( "aria-hidden",true);	
							// jQuery('#registerPopUpModal').hide();
							// jQuery( '.modal-backdrop').remove();
							// $currentUrl = jQuery(location).attr('href');
							jQuery("#registerModalLabel").text('Register Successfully');
							jQuery("#register-closing-notification").html('<div class="vspace8 clearfix"></div><p>This window will automatically close in few seconds</p>');
							location.reload();
                        	// window.location = parsedJson.url;
                        	 
                         }
                          jQuery('#sns_ajaxfilter .bg').height('100%');
						 jQuery('#sns_ajaxfilter').fadeOut(600);
                      }
                });
            }
        });


        /* Forgot Password */
        jQuery('#gform-forgot-password').submit(function(event){
            event.preventDefault();
            if(!jQuery('#gform-forgot-password div input').hasClass('validation-failed')){
                var data = jQuery('#gform-forgot-password').serialize();
                jQuery('#footer-ajax-loader3').css('background', 'url(<?php echo $this->getSkinUrl('ajaxlogin/images/opc-ajax-loading-black.gif') ?>) no-repeat top right')
                //alert(data);
                jQuery.ajax({
                      url: "<?php echo $this->getUrl('ajaxlogin/account/guruthemeForgotPass') ?>",
                      type : 'post',
                      data: data,
                      success: function(data){
                    	  var parsedJson = jQuery.parseJSON(data);                      
                          if(parsedJson.message){
                        	  new Messi(parsedJson.message);
                          }
                          /*if(parsedJson.success){
                        	 window.location = parsedJson.url;
                        	 
                         }*/
                         jQuery('#footer-ajax-loader3').css('background', 'none');
                            //jQuery('#newsletter').val('');
                      }
                });
            }
        });
        
});


</script>
