<?php $_code = $this->getMethodCode() ?>
<?php $_logos = $this->getLogosToDisplay();?>
<?php $_turnOffTypeValidation = in_array('DIN', $this->getCcAvailableTypes()); ?>

<iframe id="iframePxFusion" allowtransparency="true" frameborder="0"  name="iframePxFusion" style="display:none;" src="<?php echo $this->getJsUrl() ?>blank.html" height="100" width="300" scrolling="yes"></iframe>

<script type="text/javascript">
    window.foomanSuccessUrl = '';
    if (typeof AWOnestepcheckoutForm === 'function') {
        AWOnestepcheckoutForm.prototype.onComplete  = AWOnestepcheckoutForm.prototype.onComplete.wrap(function(originalNexStep, transport){
            window.foomanSuccessUrl = this.successUrl;
            if(payment.currentMethod != 'foomandpsprofusion') {
                return originalNexStep(transport);
            }
            checkout.setLoadWaiting('review');
            //TODO bring back check to only change pxfusion payments
            if (transport && transport.responseText) {
                try{
                    response = eval('(' + transport.responseText + ')');
                }
                catch (e) {
                    response = {};
                }
                if (response.success) {

                    var iframe = $('iframePxFusion');
                    var doc = null;

                    if(iframe.contentDocument) {
                        doc = iframe.contentDocument;
                    } else if(iframe.contentWindow) {
                        doc = iframe.contentWindow.document;
                    } else if(iframe.document) {
                        doc = iframe.document;
                    }

                    doc.body.innerHTML = "";

                    pxFusionForm = doc.createElement('form');
                    pxFusionForm.id = 'pxfusion_form';
                    pxFusionForm.method = 'post';
                    pxFusionForm.action = '<?php echo Fooman_DpsPro_Model_Method_PxFusion::URL_FORM_SUBMIT;?>';
                    submit = doc.createElement('submit');
                    pxFusionForm.appendChild(submit);

                    var cardholder = doc.createElement('input');
                    cardholder.id = 'CardHolderName';
                    cardholder.name = 'CardHolderName';
                    cardholder.value = $('foomandpsprofusion_cc_owner').getValue();
                    pxFusionForm.appendChild(cardholder);

                    var ccNumber = doc.createElement('input');
                    ccNumber.id = 'CardNumber';
                    ccNumber.name = 'CardNumber';
                    ccNumber.value = $('foomandpsprofusion_cc_number').getValue();
                    pxFusionForm.appendChild(ccNumber);

                    var expirationMonth = doc.createElement('input');
                    expirationMonth.id = 'ExpiryMonth';
                    expirationMonth.name = 'ExpiryMonth';
                    expirationMonth.value = $('foomandpsprofusion_expiration').getValue();
                    if($('foomandpsprofusion_expiration').getValue().length == 1) {
                        expirationMonth.value = '0' + $('foomandpsprofusion_expiration').getValue();
                    }
                    pxFusionForm.appendChild(expirationMonth);

                    var expirationYear = doc.createElement('input');
                    expirationYear.id = 'ExpiryYear';
                    expirationYear.name = 'ExpiryYear';
                    expirationYear.value = $('foomandpsprofusion_expiration_yr').getValue().replace('20', '');
                    pxFusionForm.appendChild(expirationYear);

                    var cvc2 = doc.createElement('input');
                    cvc2.id = 'Cvc2';
                    cvc2.name = 'Cvc2';
                    cvc2.value = $('foomandpsprofusion_cc_cid').getValue();
                    pxFusionForm.appendChild(cvc2);

                    var sessionId = doc.createElement('input');
                    sessionId.id = 'SessionId';
                    sessionId.name = 'SessionId';
                    sessionId.value = response.redirect;
                    pxFusionForm.appendChild(sessionId);

                    var dpsAction = doc.createElement('input');
                    dpsAction.id = 'Action';
                    dpsAction.name = 'Action';
                    dpsAction.value = 'Add';
                    pxFusionForm.appendChild(dpsAction);

                    var dpsObject = doc.createElement('input');
                    dpsObject.id = 'Object';
                    dpsObject.name = 'Object';
                    dpsObject.value = 'DpsPxPay';
                    pxFusionForm.appendChild(dpsObject);

                    doc.body.appendChild(pxFusionForm);

                    //TODO convert iframe to just a AJAX post request
                    //Not possible due to cross domain calls restrictions.
                    //TODO actually check what the return value is
                    //TODO update the order status to processing and create invoice = extra controller
                    //does PxFusion also offer FailProofNotifications?
                    //TODO see if we can handle payment failure case better, restore quote and allow resubmitting?
                    pxFusionForm.submit();
                } else if("is_hosted_pro" in response && response.is_hosted_pro) {
                    this.popup.showPopupWithDescription(response.update_section.html);
                    var iframe = this.popup.contentContainer.select('#hss-iframe').first();
                    iframe.observe('load', function(){
                        $('hss-iframe').show();
                        $('iframe-warning').show();
                    });
                } else {
                    var msg = response.messages;
                    if (typeof(msg) == 'object') {
                        msg = msg.join("\n");
                    }
                    if (msg) {
                        alert(msg);
                    }
                    this.enablePlaceOrderButton();
                    this.hidePleaseWaitNotice();
                    this.hideOverlay();
                }
            }

            return;
        });
    }
</script>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry <?php $_turnOffTypeValidation? '': 'validate-cc-type-select'?>">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li>
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
        <script type="text/javascript">
        //<![CDATA[
        var DINChecked<?php echo $_code ?> = function() {
            var elm = $('<?php echo $_code ?>_cc_type');
            if(elm){
                if (elm.value=='DIN') {
                    $('<?php echo $_code ?>_cc_type').removeClassName('validate-cc-type-select');
                    $('<?php echo $_code ?>_cc_number').removeClassName('validate-cc-type');
                    $('<?php echo $_code ?>_cc_cid').removeClassName('validate-cc-cvn');
                } else {
                    $('<?php echo $_code ?>_cc_type').addClassName('validate-cc-type-select');
                    $('<?php echo $_code ?>_cc_number').addClassName('validate-cc-type');
                    $('<?php echo $_code ?>_cc_cid').addClassName('validate-cc-cvn');
                }
            }
        };
        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', DINChecked<?php echo $_code ?>);
        DINChecked<?php echo $_code ?>();

        //]]>

        </script>
    </li>
    <?php endif; ?>
    <?php if ($this->hasSsCardType()): ?>
    <li>
    <ul class="inner-form" id="<?php echo $_code ?>_cc_type_ss_div">
        <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo Only') ?></label></li>
        <li>
            <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
            <span class="input-box">
                <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
            </span>
        </li>

        <li>
            <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                    <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <li class="adv-container">&nbsp;</li>
   </ul>
        <script type="text/javascript">
        //<![CDATA[
        var SSChecked<?php echo $_code ?> = function() {
            var elm = $('<?php echo $_code ?>_cc_type');
            if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                $('<?php echo $_code ?>_cc_type_ss_div').show();
            } else {
                $('<?php echo $_code ?>_cc_type_ss_div').hide();
            }
        };

        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
        //SSChecked<?php echo $_code ?>();

        //]]>

        </script>
</li>
<?php endif; ?>
<?php if (count($_logos) > 0): ?>
<li>
    <?php foreach($_logos as $_logo): ?>
        <img src="<?php echo $this->getSkinUrl('images/magebase/dps/'.$_logo); ?>" alt="" />
    <?php endforeach ?>

    <a href="http://www.paymentexpress.com/About/About_DPS/Privacy_Policy" target="_blank">
        <img src="<?php echo $this->getSkinUrl('images/magebase/dps/dpspxlogo.png'); ?>" alt="DPS"/><br/>
        <small>DPS <?php echo $this->__('Privacy Policy') ?></small>
    </a>
</li>
<?php endif;?>
<?php if($this->displayAddCcSave()):?>
<li class="control">
    <input class="checkbox" type="checkbox"
           id="<?php echo $_code ?>_cc_save"
           name="payment[cc_save]"
           title="<?php echo $this->__('Save my payment details for next time') ?>"
           value="1" />
    <label for="<?php echo $_code ?>_cc_save"><?php echo $this->__('Save my payment details for next time') ?></label>
</li>
<?php else: ?>
<li style="display:none;">
<input type="hidden"
       id="<?php echo $_code ?>_cc_save"
       name="payment[cc_save]"
       title="<?php echo $this->__('Save my payment details for next time') ?>"
       value="0" />
</li>
<?php endif;?>

</ul>