<?php
/**
 * Magebase
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magebase. (http://magebase.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="form-group">
	<label for="<?php echo $this->getFieldId('myorder_customercomment')?>" class="col-sm-2 control-label"><?php echo $this->__('Shipping Attention/Comments') ?></label>
	<div class="col-sm-10 form-group customer-comment-block">
		<textarea id="<?php echo $this->getFieldId('myorder_customercomment')?>" name="<?php echo $this->getFieldName('myorder_customercomment')?>" class="form-control customer-comment-box" <?php echo $this->getFieldParams() ?>><?php echo $this->htmlEscape($this->getComment()) ?></textarea>
	</div>
</div>
