<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to a Commercial Software License.
 * No sharing - This file cannot be shared, published or
 * distributed outside of the licensed organisation.
 * No Derivatives - You can make changes to this file for your own use,
 * but you cannot share or redistribute the changes.
 * This Copyright Notice must be retained in its entirety.
 * The full text of the license was supplied to your organisation as
 * part of the licensing agreement with mVentory.
 *
 * @package MVentory/TradeMe
 * @copyright Copyright (c) 2014 mVentory Ltd. (http://mventory.com)
 * @license Commercial
 */

?>

<div class="entry-edit-head collapseable">
  <strong>CSV configuration file fields description</strong>
</div>

<div class="box">
  <h4>This section explains settings used in the CSV configuration file. See Settings section above for more info.</h4>

  <p>Shipping options can be configured per account per shipping method. In addition, either weight-based or price-based (but not both) rules can be configured. Configuration CSV file consists of 4 selectors (first four columns: account, shipping method, max weight, max price) and a number of configuration fields (remaining columns). For a particular product, the file is scanned from the first row down until a row with matching selectors is found - the configuration values from this row are then used to create a TradeMe listing.</p>

  <h5>Description of selectors columns:</h5>

  <table class="trademe-setting-help-table">
    <tr>
      <td>
        Account
      </td>
      <td>
        Account name (as specified above), where a listing is being created.
      </td>
    </tr>
    <tr>
      <td>
        Shipping method
      </td>
      <td>
        Values from the shipping method attribute (specified above). Each shipping method can be configured separately in separate rows or an asterix can be used as a wildcat to configure all shipping types that do not have their own configurations.
      </td>
    </tr>
    <tr>
      <td>
        Maximum weight
      </td>
      <td>
        Product weight must be less or equal to the value in this column. Arrange values in ascending order. The use of weight and price rules is mutually exclusive for each account/shipping method combination.
      </td>
    </tr>
    <tr>
      <td>
        Maximum price
      </td>
      <td>
        Product price must be less or equal to the value in this column. Arrange values in ascending order. The use of weight and price rules is mutually exclusive for each account/shipping method combination.
      </td>
    </tr>
  </table>

  <h5>Description of configuration fields:</h5>

  <table class="trademe-setting-help-table">
    <tr>
      <td>
        Free shipping cost
      </td>
      <td></td>
    </tr>
    <tr>
      <td>
        Allow Buy Now
      </td>
      <td>
        Buy Now option will be added to each auction. Buy Now price will be the same as the starting price.
      </td>
    </tr>
    <tr>
      <td>
        Avoid withdrawal
      </td>
      <td>
        Instead of withdrawing an auction, the price will be increased by XXX and the auction will be left to expire.
      </td>
    </tr>
    <tr>
      <td>
        Add fees
      </td>
      <td>
        Trade Me fees will be added to product cost to calculate the starting price.
        <br />
        The field has 3 options:
        <ul>
          <li><code>0</code> or empty - No comission</li>
          <li><code>1</code> or <code>always</code> - Always add commission</li>
          <li><code>2</code> or <code>special</code> - Only if the product has a current special price</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>
        Allow pickup
      </td>
      <td>
        'Pick-ups are allowed' will be set in auction shipping details.
      </td>
    </tr>
    <tr>
      <td>
        Add category image
      </td>
      <td>
        An category image to appear in category listing will be added to the auction.
      </td>
    </tr>
    <tr>
      <td>
        Buyer ID
      </td>
      <td>
        <ul>
          <li>Leave blank if Magento should not create any orders for sold listings. Quantities will not be updated either.</li>
          <li>If buyer ID (=customer id in Magento) is specified Magento will attempt to download customer details from TM and allocate the order to this customer in Magento (create new if needed)</li>
          <li>If the customer details cannot be downloaded are insufficient then this buyer ID is used</li>
          <li>Make sure the customer is configured correctly. Disable State/Province for NZ, make postcodes optional, create a test purchase using this customer.</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>
        Listing duration
      </td>
      <td>
        Duration of a product listing in days.
      </td>
    </tr>
    <tr>
      <td>
        Shipping options
      </td>
      <td>
        Use one of the following options:
        <ul>
          <li>Pairs of values (shipping cost,shipping method - e.g. 5,Courier), separated by a new line i.e. one method per line.</li>
          <li>Text 'free' for free shipping (cannot be used in combination with any other shipping method.</li>
          <li>Empty cell - to indicate shipping method to be arranged.</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>
        Footer description
      </td>
      <td>
        Any text that should be attached to the auction description as a footer.
        <br />
        The following special tags can be used:
        <ul>
          <li><code>{{url}}</code> - product URL</li>
          <li><code>{{fd}}</code> - product description</li>
          <li><code>{{sd}}</code> - product short description</li>
          <li><code style="text-decoration: line-through">{{fs}}</code> - free shipping text (not used currently)</li>
          <li><code>{{attrs}}</code> - product attributes (only visible on frontend)</li>
        </ul>
      </td>
    </tr>
  </table>
</div>
