<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to a Commercial Software License.
 * No sharing - This file cannot be shared, published or
 * distributed outside of the licensed organisation.
 * No Derivatives - You can make changes to this file for your own use,
 * but you cannot share or redistribute the changes.
 * This Copyright Notice must be retained in its entirety.
 * The full text of the license was supplied to your organisation as
 * part of the licensing agreement with mVentory.
 *
 * @package MVentory/TradeMe
 * @copyright Copyright (c) 2014-2015 mVentory Ltd. (http://mventory.com)
 * @license Commercial
 */

?>

<div class="entry-edit-head collapseable">
  <strong>TradeMe Integration</strong>
</div>

<div class="box">
	<p>This extension connects your Magento directly to TradeMe via TradeMe API to create listings from Magento products and keep the inventory in sync.</p>

	<h4>1. Configure settings at the Global scope.</h4>
	<p>Go through every setting, read the additional information behind [?] icon and fill in everything that makes sense. Some settings are optional.</p>

	<h4>2. Configure settings at the Website scope.</h4>
	<p>Switch to the website level using the dropdown at the top left corner of the page and complete the configuration there.<br />Different websites within the same Magento installation can be configured differently.</p>

	<h4>3. Configure TradeMe categories mapping per attribute set.</h4>
	<p>Instead of selecting TradeMe categories for every product you can create rules for mapping your product types to TradeMe categories. E.g. a mug can go to a dozen different categories on TradeMe. You can configure a rule based on the mug's type, size, purpose, condition, etc.</p>
	<p>Open an attribute set, scroll down to TradeMe category mapping section and follow the instructions on the screen.</p>

	<h4>4. Manual listing</h4>
	<p>Open a product details page in the admin and click on TradeMe tab. Check the default settings, select a TradeMe category and press [Submit] button.</p>
	<p>The settings will be remembered for the next time this product is relisted.</p>

	<h4>5. Automated listing on a schedule.</h4>
	<p>The best way of using this extension is to configure everything, start the cron and let it list the products on a schedule giving you constant presence on TradeMe.</p>

	<h4>Troubleshooting</h4>
	<p>Make sure Magento logging is enabled and check trademe.log for detailed information on all extension activities.</p>

	<h4>Help and Support</h4>
	<p>Contact mVentory on <a href="mailto:support@mventory.com">support@mventory.com</a> for assistance.</p>
</div>
