<?php
$_helper          =  Mage::helper('catalogsearch');
$_value           = $_helper->getEscapedQueryText();
$_currentCategory = Mage::getSingleton('core/app')->getRequest()->getParam('cat');
$_currentAttribute = Mage::getSingleton('core/app')->getRequest()->getParam('attr');
$_filterType      = $this->getFilterType();
$_url             = $this->getAjaxUrl();
?>
<form id="search_mini_form" action="<?php echo $_helper->getResultUrl() ?>"    method="get"
    class="searchautocomplete UI-SEARCHAUTOCOMPLETE"
    data-url="<?php echo $_url ?>"
    data-minchars="<?php echo Mage::getStoreConfig('searchautocomplete/general/min_chars') ?>"
    data-delay="<?php echo Mage::getStoreConfig('searchautocomplete/general/delay') ?>">

    <div class="form-search input-group">
        <input id="search" type="text" onblur="this.placeholder = 'enter your text'" onfocus="this.placeholder = ''" placeholder="Product Search. e.g '1700mm Bath'" autocomplete="off"  name="<?php echo $_helper->getQueryParamName() ?>" value="<?php echo $_helper->getEscapedQueryText() ?>" class="form-control UI-SEARCH UI-NAV-INPUT" maxlength="<?php echo $_helper->getMaxQueryLength();?>" />

		<span class="input-group-btn">
			<button type="submit" title="<?php echo $this->__('Search') ?>" class="btn btn-search"><?php echo $this->__('GO!');?></button>
		</span>
		<br>
		<div class="clearfix"></div>
        <div class="searchautocomplete-loader UI-LOADER" style="display:none;"></div>
        <div style="display:none" id="search_autocomplete" class="UI-PLACEHOLDER search-autocomplete search-results"></div>
		
		<?php if ($_filterType == 'category'): ?>
        <div class="nav-search-in">
            <span class="category-fake UI-CATEGORY-TEXT"><?php echo $this->__('All') ?></span>
            <span class="nav-down-arrow"></span>
            <select name="cat" class="category UI-CATEGORY">
                <option value="0"><?php echo $this->__('All') ?></option>
                <?php foreach ($this->getCategories() as $_category): ?>
                <option value="<?php echo $_category->getId() ?>" <?php if ($_currentCategory == $_category->getId()): ?>selected<?php endif ?>>
                    <?php echo $_category->getName() ?>
                </option>
                <?php endforeach ?>
            </select>
        </div>
        <?php elseif ($_filterType == 'attribute'): ?>
            <div class="nav-search-in">
                <span class="category-fake UI-CATEGORY-TEXT"><?php echo $this->__('All') ?></span>
                <span class="nav-down-arrow"></span>
                <select name="attr" class="category UI-CATEGORY">
                    <option value="0"><?php echo $this->__('All') ?></option>
                    <?php foreach ($this->getAttributes() as $_code => $_name): ?>
                    <option value="<?php echo $_code ?>" <?php if ($_currentAttribute == $_code): ?>selected<?php endif ?>>
                        <?php echo $_name ?>
                    </option>
                    <?php endforeach ?>
                </select>
            </div>
        <?php endif ?>
    </div>
</form>
