<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Creative Commons License BY-NC-ND.
 * NonCommercial — You may not use the material for commercial purposes.
 * NoDerivatives — If you remix, transform, or build upon the material,
 * you may not distribute the modified material.
 * See the full license at http://creativecommons.org/licenses/by-nc-nd/4.0/
 *
 * See http://mventory.com/legal/licensing/ for other licensing options.
 *
 * @package MVentory/API
 * @copyright Copyright (c) 2014 mVentory Ltd. (http://mventory.com)
 * @license http://creativecommons.org/licenses/by-nc-nd/4.0/
 * @author Anatoly A. Kazantsev <anatoly@mventory.com>
 */
?>

<div>
<ul class="messages">
  <li class="notice-msg">
    <ul>
      <li><?php echo $this->__('This tab controls use and appearance of this attribute in mVentory App. <a href="http://mventory.com">Read more&hellip;</a>') ?></li>
    </ul>
  </li>
</ul>
</div>

<div class="entry-edit">
  <?php echo $this->getFormHtml();?>
</div>

<?php echo $this->getChildHtml('form_after');?>
