<?php
/**
 * MageBase DPS Payment Express
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with Magento in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    MageBase
 * @package     MageBase_DpsPaymentExpress
 * @author      Kristof Ringleff
 * @copyright   Copyright (c) 2009 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @copyright   Copyright (c) 2010 MageBase (http://www.magebase.com)
 * @copyright   Copyright (c) 2010 Fooman Ltd (http://www.fooman.co.nz)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php $_code=$this->getMethodCode() ?>
<?php $_logos = $this->getLogosToDisplay();?>
<?php $_turnOffTypeValidation = in_array('DIN', $this->getCcAvailableTypes()); ?>
<div class="col-sm-12" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<div class="form-group">	
        <label for="<?php echo $_code ?>_cc_owner" class="required col-sm-4 control-label"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="col-sm-5">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="form-control required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" placeholder="Name"/>
        </div>
	</div>	
 	<div class="form-group">
        <label for="<?php echo $_code ?>_cc_type" class="required col-sm-4 control-label"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="col-sm-5">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry form-control <?php $_turnOffTypeValidation? '': 'validate-cc-type-select'?>">
                <option value=""><?php echo $this->__('-- CARD TYPE --')?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
	</div>	
	<div class="form-group">
        <label for="<?php echo $_code ?>_cc_number" class="required col-sm-4 control-label"><em>*</em><?php echo $this->__('Credit Card No.') ?></label>
        <div class="col-sm-5">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="form-control validate-cc-number validate-cc-type" value="" placeholder="XXXXXXXXXXXXXXXX" />
        </div>
    </div>
	<div class="form-group">
        <label for="<?php echo $_code ?>_expiration" class="required col-sm-4 control-label"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="col-sm-5">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry form-control">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
		</div>
	</div>	
	<div class="form-group">
		<label for="InputEmail2" class="col-sm-4 control-label">* Expiration Year</label>	
		<div class="col-sm-5">            
			<div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="form-control year required-entry ">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
		</div>	
	</div>
	<?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
 	<div class="form-group">
        <label for="<?php echo $_code ?>_cc_cid" class="required col-sm-4 control-label"><em>*</em><?php echo $this->__('Card Verification Number') ?><a href="#" class="cvv-what-is-this"><?php echo $this->__('[?]') ?></a></label>
        <div class="col-sm-5">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="form-control cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
		</div>
        <script type="text/javascript">
        //<![CDATA[
        var DINChecked<?php echo $_code ?> = function() {
            var elm = $('<?php echo $_code ?>_cc_type');
            if(elm){
                if (elm.value=='DIN') {
                    $('<?php echo $_code ?>_cc_type').removeClassName('validate-cc-type-select');
                    $('<?php echo $_code ?>_cc_number').removeClassName('validate-cc-type');
                    $('<?php echo $_code ?>_cc_cid').removeClassName('validate-cc-cvn');
                } else {
                    $('<?php echo $_code ?>_cc_type').addClassName('validate-cc-type-select');
                    $('<?php echo $_code ?>_cc_number').addClassName('validate-cc-type');
                    $('<?php echo $_code ?>_cc_cid').addClassName('validate-cc-cvn');
                }
            }
        };
        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', DINChecked<?php echo $_code ?>);
        DINChecked<?php echo $_code ?>();

        //]]>

        </script>
	</div>	
    <?php endif; ?>
    <?php if ($this->hasSsCardType()): ?>
    <li>
    <ul class="inner-form" id="<?php echo $_code ?>_cc_type_ss_div">
        <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo Only') ?></label></li>
        <li>
            <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
            <span class="input-box">
                <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
            </span>
        </li>

        <li>
            <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                    <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <li class="adv-container">&nbsp;</li>
   </ul>
        <script type="text/javascript">
        //<![CDATA[
        var SSChecked<?php echo $_code ?> = function() {
            var elm = $('<?php echo $_code ?>_cc_type');
            if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                $('<?php echo $_code ?>_cc_type_ss_div').show();
            } else {
                $('<?php echo $_code ?>_cc_type_ss_div').hide();
            }
        };

        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
        //SSChecked<?php echo $_code ?>();

        //]]>

        </script>
</li>
<?php endif; ?>
<?php if($this->displayAddCcSave()) :?>
    <li class="control">
        <input class="checkbox" type="checkbox"
               id="<?php echo $_code ?>_cc_save"
               name="payment[cc_save]"
               title="<?php echo $this->__('Save my payment details for next time') ?>"
               value="1" />
        <label for="<?php echo $_code ?>_cc_save"><?php echo $this->__('Save my payment details for next time') ?></label>
    </li>
<?php endif;?>
<hr>
<?php if (count($_logos) > 0): ?>
<div class="bs-callout bs-callout-info">
    <a href="http://www.paymentexpress.com/About/About_DPS/Privacy_Policy" target="_blank">
        <img src="<?php echo $this->getSkinUrl('images/magebase/dps/dpspxlogo.png'); ?>" alt="DPS"/>
        <small>DPS <?php echo $this->__('Privacy Policy') ?></small>
    </a>
	<span class="pull-right">
	<?php foreach($_logos as $_logo): ?>
        <img src="<?php echo $this->getSkinUrl('images/magebase/dps/'.$_logo); ?>" alt="" />
    <?php endforeach ?>
	</span>
</div>	
<?php endif;?>
</div>
