<?php
$options = $this->getConfigObject();
if( $options->list_products_by == 'order' ){
	$list = $this->getListByOrder();
} else {
	$list = $this->getListByCategory();
}
?>
<?php if(!empty($list)){ ?>
	<div class="clearfix vspace8"></div>
	<div class="row">	
	<?php $_collectionSize = count($list); ?>
	<?php $_columnCount = 4; ?>
	<?php $i=0;
		foreach($list as $items) :
			$child_items = isset($items->child)?$items->child:'';
	?>
			<div class="wrap">
			<?php
				if(!empty($child_items)){
					include 'items.phtml';
				}else{
			?>
				<div class="content-loading"></div>
			<?php
				} 
			?>
			<?php
				$scrnWidth = Mage::getSingleton('core/session')->getScreenWidth();
				if($scrnWidth && $scrnWidth>=1280 && $scrnWidth<1400){
					if($_collectionSize%4!=0){
						$ratio4 = $_collectionSize%4;
						$loop4 = 4-$ratio4;
						for($i=1;$i<=$loop4;$i++){
							echo $this->getLayout()->createBlock('cms/block')->setBlockId('filler-ad-'.$i)->toHtml();
						}
					}
				}
				if($scrnWidth && $scrnWidth>=1400){
					if($_collectionSize%5!=0){
						$ratio5 = $_collectionSize%5;
						$loop5 = 5-$ratio5;
						for($i=1;$i<=$loop5;$i++){
							echo $this->getLayout()->createBlock('cms/block')->setBlockId('filler-ad-'.$i)->toHtml();
						}
					}
				}	
			?>	
			</div>	
	<?php
		endforeach; 
	?>
		
	</div>	
	
<?php } else { echo '<p class="note-msg">' . $this->__('There are no products matching the selection.') . '</p>';}?>


