<?php
$options = $this->getConfigObject();
if( $options->list_products_by == 'order' ){
	$list = $this->getListByOrder();
} else {
	$list = $this->getListByCategory();
}
?>
<?php if(!empty($list)){ ?>
	<div class="clearfix vspace8"></div>
	<div class="row">	
	<?php $_collectionSize = count($list); ?>
	<?php $_columnCount = 4; ?>
	<?php $i=0;
		foreach($list as $items) :
			$child_items = isset($items->child)?$items->child:'';
	?>
			<div class="wrap">
			<?php
				if(!empty($child_items)){
					include 'items.phtml';
				}else{
			?>
				<div class="content-loading"></div>
			<?php
				} 
			?>
			<?php
				for($i=1;$i<=4;$i++){
					echo $this->getLayout()->createBlock('cms/block')->setBlockId('filler-ad-'.$i)->toHtml();
				}
			?>	
			</div>
			<script type="text/javascript">
				window.load = displayFillerAdd(<?php echo $_collectionSize ?>);
				window.onresize = function() {
					var $_screenWidth = screen.width;
					var $_screenHeight = screen.height;
					var $_totalProductsCounts = <?php echo $_collectionSize ?>;
		
					for (i = 1; i <= 4; i++) {
						document.getElementById('filler-ad-'+i).style.display = 'none';
					}

					if($_screenWidth && $_screenWidth>=1200 && $_screenWidth<1400){
						if($_totalProductsCounts%4!=0){
							$_ratio4 = $_totalProductsCounts%4;
							$_loop4 = 4-$_ratio4;
							for (i = 1; i <= $_loop4; i++) {
								document.getElementById('filler-ad-'+i).style.display = 'block';
							}
						}
					}
					if($_screenWidth && $_screenWidth>=1400){
						if($_totalProductsCounts%5!=0){
							$_ratio5 = $_totalProductsCounts%5;
							$_loop5 = 5-$_ratio5;
							for (i = 1; i <= $_loop5; i++) {
								document.getElementById('filler-ad-'+i).style.display = 'block';
							}
						}
					}
				}
			</script>	
	<?php
		endforeach; 
	?>
		
	</div>	
	
<?php } else { echo '<p class="note-msg">' . $this->__('There are no products matching the selection.') . '</p>';}?>


