<?php
# MC HOME PAGE  PRODUCT TABS
$options  = $this->getConfigObject();
$maxtitle = $options->item_title_max_characs;
$post     = Mage::app()->getRequest()->getPost();
$type     = $post['pdt_type'];
$catid    =	$post['catid'];

//MVENTORY: probably $params was renamed to $post
$orderby = $params['orderby'];
//orderby = $post['orderby'];

if( $type!='' ){
	if( $type == 'order' ){
		$child_items = $this->getProductsOrder($orderby);
	} else {
        //MVENTORY: it looks it is $catid instead $cat_id
		$child_items = $this->getProductsCat($cat_id);
        //$child_items = $this->getProductsCat($catid);
	}
}
if( !empty($child_items) ) {
	if( $type!='' ){
		$k = $post['numberstart'];
	} else {
		$k = 0;
	}
	$_collectionSize = count($child_items);
	if($isiPad){
		$_columnCount = 3;
	}else{
		$_columnCount = 4;
	}
	$i=0;
    foreach( $child_items  as $item ){ $k++;
        $_product = Mage::getModel('catalog/product')->load($item->id);
	?>

        <?php
        $now = date("Y-m-d");
        $newsFrom= substr($_product->getData('news_from_date'),0,10);
        $newsTo=  substr($_product->getData('news_to_date'),0,10);
		$price = $_product->getPrice();
        $finalPrice = $_product->getFinalPrice();
        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
        $class = '';
        if($now>=$newsFrom && $now<=$newsTo) $class .= ' have-iconew';
        if($specialprice) $class .= ' have-icosale';
        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
        ?>
		<div class="item product col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-15 wrap">
			<div class="product-wrap-top">
				<div class="badges">
				<?php
				if ($now>=$newsFrom && $now<=$newsTo)
				if (isset($price) && isset($finalPrice) && $finalPrice < $price && $themeConfig['general_useTagSale']==1)
					echo "<span class='ico-product ico-sale'>".floor(100-($finalPrice/$price)*100)."% OFF</span>";
				?>
				</div>
				<div class="product-image item-img<?php echo $class; ?><?php echo (count(Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages()) > 0)?' have-additional':'';?> clearfix">
					<a class="img-main" href="<?php echo $item->link ?>" title='<?php echo $item->title?>'>
						<img src="<?php // echo $item->image; ?><?php echo Mage::helper('catalog/image')->init($_product, 'small_image')->resize(250, 166); ?>" alt='<?php echo $item->title ?>'/>
					</a>
				</div>
				<div class="product-details">
					<a href="<?php echo $item->link ?>">
					<div class="product-title">
						<h2><?php echo $item->description; ?></h2>
					</div>
					</a>
					<div class="product-info row">
						<div class="col-xs-6">
							<div class="product-brand"><?php echo $this->getLayout()->createBlock('manufacturer/manufacturer')->setProduct($_product)->setTemplate('manufacturer/product_manufacturer.phtml')->toHtml(); ?></div>
						</div>
						<div class="col-xs-6">
							<?php echo $this->getPriceHtml($_product, false) ?>
						</div>
					</div>
				</div>
			</div>
			<div class="product-wrap-bottom">
				<div class="product-option">
					<?php if( $options->item_cart_disp == 1 ){ ?>
					<?php if($_product->isSaleable()): ?>
						<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-td-action btn-warning btn-md btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" data-toggle="tooltip" data-placement="top" data-original-title="<?php echo $this->__('Add to Cart') ?>"><i class="fa fa-shopping-cart"></i></button>
					<?php else: ?>
						<span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
					<?php endif; ?>
					<?php } ?>
					<?php if($this->helper('wishlist')->isAllow() && $options->item_wishlist_disp == 1 ): ?>
						<button type="button" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')" class="btn btn-td-standard1 btn-td-primary-quiet btn-danger btn-md" data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="fa fa-star"></i></button>	
					<?php endif; ?>
					<?php if($this->helper('catalog/product_compare')->getAddUrl($_product) && $options->item_compare_disp == 1): ?>
						<button type="button" onclick="setLocation('<?php echo $this->helper('catalog/product_compare')->getAddUrl($_product) ?>')" class="btn btn-td-standard1 btn-td-info-quiet btn-info btn-md" data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Add to Compare') ?>"><i class="fa fa-align-left fa-rotate-270"></i></button>
					<?php endif; ?>
				</div>
			</div>
			<div class="inner-box-sku">
				<?php echo $_product->getSku(); ?>
			</div>
		</div>
<?php }
}?>
