<?php 
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/** 
 * Template for showing options for filter as a HTML list 
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute constructor.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml 
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Mana_Filters_Block_Filter_Attribute */
?>
<?php echo Mage::helper('mana_core')->getNamedHtml('mana_filters/markup', 'before_items', array('block' => $this)) ?>


<?php
	$attributeCode = '';
    $attributeModel = $this->getAttributeModel();
    if($attributeModel) {
        $attributeCode = $attributeModel->getAttributeCode();
    }
?>
<?php if($attributeCode == 'color') : ?>
<ol class="m-filter-item-list color-filter <?php echo $this->getFilterOptions()->getIsReverse() ? 'm-reverse' : '' ?>">
<?php foreach ($this->getItems() as $_item): ?>
    <li <?php if ($_item->getMShowSelected()): ?>class="m-selected-ln-item-color"<?php else: ?>class="m-unselected-ln-item"<?php endif; ?>>
		<?php 
	    		$color = Mage::helper('i8style')->getAttributeAdminLabel($attributeCode, $_item);
	    		$color = str_replace(' ', '', $color);
				if(preg_match('/^#[a-f0-9]{6}$/i', $color)) {
					$color = $color;
				} else if(preg_match('/^[a-f0-9]{6}$/i', $color)) {
					$color = '#' . $color;
				}
	    		$colorLabel = '<span class="color-label" style="background-color: '.$color.'">x</span>';
	    		//$_item->setLabel('<span class="item">')
			?>
        <?php // MANA BEGIN ?>
        <?php if ($_item->getMSelected()): ?>
        	<a href="<?php echo $_item->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>"><span class="item"><?php echo $colorLabel; ?><span class="m-selected-filter-item"><?php echo $this->escapeHtml($_item->getLabel()) ?></span></span></a>
        <?php else : ?>
	        <?php if (!$this->getFilterOptions()->getDisableNoResultOptions() || $_item->getCount() > 0 || $_item->getMSelected()): ?>
	        <a class="item" href="<?php echo $this->urlEscape($_item->getUrl()) ?>" title="<?php echo $this->escapeHtml($_item->getLabel()) ?>"><?php echo $colorLabel; ?><span><?php echo $this->escapeHtml($_item->getLabel()) ?></span></a>
	        <?php else: echo $colorLabel . $this->escapeHtml($_item->getLabel()) ?>
	        <?php endif; ?>
        <?php endif; ?>
        <?php // MANA END ?>
        <?php if (Mage::getStoreConfigFlag('mana_filters/display/count')) : ?>
            (<?php echo $_item->getCount() ?>)
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>

<?php else : ?>
<ol class="m-filter-item-list <?php echo $this->getFilterOptions()->getIsReverse() ? 'm-reverse' : '' ?>">
<?php foreach ($this->getItems() as $_item): ?>
    <li <?php if ($_item->getMShowSelected()): ?>class="m-selected-ln-item"<?php else: ?>class="m-unselected-ln-item"<?php endif; ?>>
        <?php // MANA BEGIN ?>
        <?php if ($_item->getMSelected()): ?>
        	<a href="<?php echo $_item->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>"><span class="m-selected-filter-item"><?php echo $this->escapeHtml($_item->getLabel()) ?></span></a>
        <?php else : ?>
	        <?php if (!$this->getFilterOptions()->getDisableNoResultOptions() || $_item->getCount() > 0 || $_item->getMSelected()): ?>
	        <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>" title="<?php echo $this->escapeHtml($_item->getLabel()) ?>"><?php echo $this->escapeHtml($_item->getLabel()) ?></a>
	        <?php else: echo $this->escapeHtml($_item->getLabel()) ?>
	        <?php endif; ?>
        <?php endif; ?>
        <?php // MANA END ?>
        <?php if (Mage::getStoreConfigFlag('mana_filters/display/count')) : ?>
            (<?php echo $_item->getCount() ?>)
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>
<?php endif; ?>
<?php echo Mage::helper('mana_core')->getNamedHtml('mana_filters/markup', 'after_items', array('block' => $this)) ?>
